export const CATEGORIAS_ITEM_PREDEFINIDAS = [
  "MATERIAIS DE EXPEDIENTE E DESENHO",
  "MATERIAIS DE OFICINA E USO GERAL",
  "MATERIAIS DE INFORMATICA",
  "EQUIPAMENTOS, MOVEIS E UTENSILIOS",
  "MATERIAIS DE PINTURAS E CONSERVACAO",
  "MATERIAIS HIDRAULICOS",
  "MATERIAIS DE COPA,COZINHA E LIMPEZA",
  "MATERIAIS DE CONSTRUCAO CIVIL E PINTURA",
] as const;

export const UNIDADES_ITEM_PREDEFINIDAS = ["UND", "CX", "KG", "UN"] as const;
