-- Serviços adicionais para as gerências
-- Execute este script após o seed.sql para adicionar mais serviços

WITH periodo_ativo AS (
  SELECT id FROM periodos WHERE ativo = true LIMIT 1
)

INSERT INTO servicos (
  periodo_id,
  diretoria_id,
  gerencia_id,
  item,
  tipo_contratacao,
  unidade_demandante,
  objeto,
  justificativa,
  previsao_inicio,
  estimativa_valor,
  dotacao_orcamentaria,
  grau_prioridade,
  vinculacao,
  dependencia_descricao,
  status,
  observacao
) VALUES
  -- DC - CCRC (17-20)
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRC' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    17,
    'Servico de Apoio',
    'CCRC',
    'Gestao de atendimento ao cliente digital',
    'Melhorar experiencia do cliente nos canais digitais',
    '2026-07-01',
    95000.00,
    95000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    'Necessário treinamento da equipe antes do início'
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRC' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    18,
    'Servico Tecnico Especializado',
    'CCRC',
    'Implantacao de CRM para gestao comercial',
    'Centralizar informacoes de clientes',
    '2026-08-15',
    180000.00,
    180000.00,
    'Muito Alto',
    'Sim',
    'Depende da aprovacao do projeto piloto',
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRC' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    19,
    'Servico Continuado',
    'CCRC',
    'Manutencao de sistemas de atendimento',
    'Garantir disponibilidade dos sistemas',
    '2026-04-01',
    42000.00,
    42000.00,
    'Médio',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRC' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    20,
    'Servico de Apoio',
    'CCRC',
    'Capacitacao em atendimento ao cliente',
    'Melhorar qualidade do atendimento',
    '2026-05-10',
    28000.00,
    28000.00,
    'Baixo',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),

  -- DC - CCRR (21-24)
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRR' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    21,
    'Servico Tecnico Especializado',
    'CCRR',
    'Sistema de gestao de cobranca automatizada',
    'Reduzir inadimplencia atraves de automacao',
    '2026-06-01',
    125000.00,
    125000.00,
    'Muito Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRR' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    22,
    'Servico de Apoio',
    'CCRR',
    'Consultoria para otimizacao de processos de cobranca',
    'Melhorar eficiencia operacional',
    '2026-05-20',
    64000.00,
    64000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRR' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    23,
    'Servico Continuado',
    'CCRR',
    'Suporte a plataforma de negociacao de debitos',
    'Manter sistema operacional',
    '2026-04-01',
    36000.00,
    36000.00,
    'Médio',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRR' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    24,
    'Servico de Apoio',
    'CCRR',
    'Analise de credito e risco de inadimplencia',
    'Prevenir perdas financeiras',
    '2026-07-15',
    52000.00,
    52000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),

  -- DC - CCRF (25-28)
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRF' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    25,
    'Servico Tecnico Especializado',
    'CCRF',
    'Desenvolvimento de sistema de faturamento',
    'Modernizar processo de faturamento',
    '2026-08-01',
    210000.00,
    210000.00,
    'Muito Alto',
    'Sim',
    'Depende da integracao com ERP',
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRF' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    26,
    'Servico de Apoio',
    'CCRF',
    'Auditoria de processos de faturamento',
    'Identificar e corrigir falhas',
    '2026-06-10',
    48000.00,
    48000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRF' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    27,
    'Servico Continuado',
    'CCRF',
    'Manutencao de sistema de cadastro de clientes',
    'Garantir integridade dos dados',
    '2026-04-01',
    38000.00,
    38000.00,
    'Médio',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DC'),
    (SELECT id FROM gerencias WHERE sigla = 'CCRF' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DC')),
    28,
    'Servico de Apoio',
    'CCRF',
    'Capacitacao em gestao de cadastros',
    'Melhorar qualidade dos dados',
    '2026-05-05',
    22000.00,
    22000.00,
    'Baixo',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),

  -- PR - PRG (29-32)
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'PR'),
    (SELECT id FROM gerencias WHERE sigla = 'PRG' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'PR')),
    29,
    'Servico Tecnico Especializado',
    'PRG',
    'Consultoria em governanca corporativa',
    'Implementar melhores praticas de gestao',
    '2026-07-10',
    98000.00,
    98000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'PR'),
    (SELECT id FROM gerencias WHERE sigla = 'PRG' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'PR')),
    30,
    'Servico de Apoio',
    'PRG',
    'Treinamento em gestao de riscos',
    'Capacitar equipe para identificacao de riscos',
    '2026-05-20',
    32000.00,
    32000.00,
    'Médio',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'PR'),
    (SELECT id FROM gerencias WHERE sigla = 'PRG' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'PR')),
    31,
    'Servico Continuado',
    'PRG',
    'Suporte a planejamento estrategico',
    'Apoiar elaboracao do plano estrategico',
    '2026-04-01',
    55000.00,
    55000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'PR'),
    (SELECT id FROM gerencias WHERE sigla = 'PRG' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'PR')),
    32,
    'Servico de Apoio',
    'PRG',
    'Analise de indicadores de desempenho',
    'Monitorar metas institucionais',
    '2026-06-15',
    44000.00,
    44000.00,
    'Médio',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),

  -- PR - PRJ (33-36)
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'PR'),
    (SELECT id FROM gerencias WHERE sigla = 'PRJ' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'PR')),
    33,
    'Servico Tecnico Especializado',
    'PRJ',
    'Gestao de portfolio de projetos',
    'Otimizar recursos e entregas',
    '2026-08-01',
    115000.00,
    115000.00,
    'Muito Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'PR'),
    (SELECT id FROM gerencias WHERE sigla = 'PRJ' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'PR')),
    34,
    'Servico de Apoio',
    'PRJ',
    'Capacitacao em metodologias ageis',
    'Melhorar gestao de projetos',
    '2026-05-15',
    38000.00,
    38000.00,
    'Médio',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'PR'),
    (SELECT id FROM gerencias WHERE sigla = 'PRJ' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'PR')),
    35,
    'Servico Continuado',
    'PRJ',
    'Ferramenta de gestao de projetos',
    'Centralizar informacoes de projetos',
    '2026-04-01',
    72000.00,
    72000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'PR'),
    (SELECT id FROM gerencias WHERE sigla = 'PRJ' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'PR')),
    36,
    'Servico de Apoio',
    'PRJ',
    'Analise de viabilidade de projetos',
    'Avaliar projetos antes da execucao',
    '2026-06-20',
    56000.00,
    56000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),

  -- DE - EOBR (37-40)
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DE'),
    (SELECT id FROM gerencias WHERE sigla = 'EOBR' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DE')),
    37,
    'Servico Tecnico Especializado',
    'EOBR',
    'Fiscalizacao de obras de grande porte',
    'Garantir qualidade das entregas',
    '2026-07-01',
    280000.00,
    280000.00,
    'Muito Alto',
    'Sim',
    'Vinculado ao cronograma de obras',
    'rascunho',
    'Necessário equipe especializada'
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DE'),
    (SELECT id FROM gerencias WHERE sigla = 'EOBR' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DE')),
    38,
    'Servico de Apoio',
    'EOBR',
    'Consultoria em gestao de contratos de obras',
    'Otimizar gestao contratual',
    '2026-05-15',
    62000.00,
    62000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DE'),
    (SELECT id FROM gerencias WHERE sigla = 'EOBR' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DE')),
    39,
    'Servico Continuado',
    'EOBR',
    'Suporte tecnico a projetos de engenharia',
    'Apoiar equipe tecnica',
    '2026-04-01',
    88000.00,
    88000.00,
    'Alto',
    'Não',
    NULL,
    'rascunho',
    NULL
  ),
  (
    (SELECT id FROM periodo_ativo),
    (SELECT id FROM diretorias WHERE sigla = 'DE'),
    (SELECT id FROM gerencias WHERE sigla = 'EOBR' AND diretoria_id = (SELECT id FROM diretorias WHERE sigla = 'DE')),
    40,
    'Servico de Apoio',
    'EOBR',
    'Levantamento topografico e planialtimetrico',
    'Subsidiar projetos de engenharia',
    '2026-06-10',
    75000.00,
    75000.00,
    'Médio',
    'Não',
    NULL,
    'rascunho',
    NULL
  );

-- Verificar serviços inseridos
SELECT 
  s.item,
  s.objeto,
  g.sigla as gerencia,
  d.sigla as diretoria,
  s.grau_prioridade,
  s.estimativa_valor,
  s.status
FROM servicos s
JOIN gerencias g ON s.gerencia_id = g.id
JOIN diretorias d ON s.diretoria_id = d.id
ORDER BY s.item;
